version: '3.4'

services:
  consoleapp1:
    image: consoleapp1:dev
    build:
      target: base
    environment:
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_consoleapp1$
    volumes:
      - C:\Users\Luis\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1:C:\app
      - C:\Users\Luis\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_consoleapp1$
    entrypoint: cmd /c "set DISABLE_PERFORMANCE_DEBUGGER=1 & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_consoleapp1$ bin\\Debug\\netcoreapp2.0\\ConsoleApp1.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"